[isp_core_routers]
ISP-CORE-RTR01 ansible_host=10.10.116.21
ISP-CORE-RTR02 ansible_host=10.10.116.22
ISP-CORE-RTR03 ansible_host=10.10.116.23
ISP-CORE-RTR04 ansible_host=10.10.116.24

[isp_core_routers:vars]
ansible_user=automation
ansible_password=asdfgh2#Q2022!
ansible_network_os=cisco.ios.ios
ansible_connection=ansible.netcommon.network_cli
ansible_become=yes
ansible_become_method=enable
ansible_become_password=asdfgh2#Q2022!

[isp_test_routers]
ISP-CORE-RTR01
ISP-CORE-RTR02
ISP-CORE-RTR03
ISP-CORE-RTR04


[vmx_bgp]
SITE-A-RED-RTR01 ansible_host=10.10.116.25

[vmx_bpg:vars]
ansible_user=automation
ansible_password=asdfgh2#Q2022!
ansible_network_os=juniper.device.junos
ansible_connection=ansible.netcommon.netconf


[cisco_bgp]
ISP-CORE-RTR03
ISP-CORE-RTR04

[cisco_bgp_speaking_routers:vars]
ansible_user=automation
ansible_password=asdfgh2#Q2022!
ansible_network_os=cisco.ios.ios
ansible_connection=ansible.netcommon.network_cli
ansible_become=yes
ansible_become_method=enable
ansible_become_password=asdfgh2#Q2022!

