---

# host_vars/ISP-CORE-RTR03.yml

my_interfaces:
  - name: Loopback0
    ip: 3.3.3.3
    mask: 255.255.255.255
    isis_enabled: true
    mpls_enabled: true
  - name: GigabitEthernet1
    ip: 10.10.34.3
    mask: 255.255.255.0
    isis_enabled: true
    mpls_enabled: true
  - name: GigabitEthernet2
    ip: 10.10.13.3
    mask: 255.255.255.0
    isis_enabled: true
    mpls_enabled: true
  - name: GigabitEthernet3
    ip: 10.10.24.3
    mask: 255.255.255.0
    isis_enabled: true
    mpls_enabled: true
  - name: GigabitEthernet4
    ip: 31.31.31.3
    mask: 255.255.255.248
    isis_enabled: false
    mpls_enabled: false
 


isis_net: "49.0001.0000.0000.0003.00"
isis_process_id: 100
sr_node_sid: 3

