---

# host_vars/ISP-CORE-RTR04.yml

my_interfaces:
  - name: Loopback0
    ip: 4.4.4.4
    mask: 255.255.255.255
    isis_enabled: true
    mpls_enabled: true
  - name: GigabitEthernet1
    ip: 10.10.34.4
    mask: 255.255.255.0
    isis_enabled: true
    mpls_enabled: true
  - name: GigabitEthernet2
    ip: 10.10.24.4
    mask: 255.255.255.0
    isis_enabled: true
    mpls_enabled: true
  - name: GigabitEthernet3
    ip: 10.10.14.4
    mask: 255.255.255.0
    isis_enabled: true
    mpls_enabled: true
  - name: GigabitEthernet4
    ip: 41.41.41.4
    mask: 255.255.255.248
    isis_enabled: false
    mpls_enabled: false
    bgp_enabled: true

isis_net: "49.0001.0000.0000.0004.00"
isis_process_id: 100
sr_node_sid: 4

bgp_process_id: 100
