---
- name: "02 - Configure ISIS"
  hosts: isp_test_routers
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Configure ISIS on ISP Core Routers
      cisco.ios.ios_config:
        parents: "router isis {{ isis_process_id }}"
        lines:
          - "net {{ isis_net }}"
          - "metric-style wide"
          - "is-type level-2-only"
          - "log-adjacency-changes"
        match: line

    - name: Enable ISIS on specific Interfaces
      cisco.ios.ios_config:
        parents: "interface {{ item.name }}"
        lines:
          - "ip router isis {{ isis_process_id }}"
        match: line
      loop: "{{ my_interfaces }}"
      when: item.isis_enabled | bool

    - name: Wait For IS-IS Adjacency To Form
      ansible.builtin.pause:
        seconds: 10

    - name: Verify ISIS Adjacency
      cisco.ios.ios_command:
        commands:
          - "show isis neighbors"
      register: isis_output

    - name: Display IS-IS Neighbors
      ansible.builtin.debug:
        var: isis_output.stdout_lines